spring.application.name=LibraryManagementSystem

# Database Configuration (FIXED)
spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:32529/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MhoFKMqVUwJmJQWNrquOZMZkDYAobwod
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server
server.port=${PORT:8080}

# JSP
spring.mvc.view.suffix=.jsp